### ISSUE TITLE
Uhhhhh, shit is fucked

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/mrspec#11]
```
.
├── lib
│   └── bowling.rb
└── spec
    └── whatevz_spec.rb

2 directories, 2 files
```

lib/bowling.rb

``` ruby
class Bowling
  def self.score(rolls)
    new(rolls).score
  end

  def initialize(rolls)
    @rolls = rolls
  end

  def score(total=0)
    current = rolls.shift
    if strike?
      current + rolls[1] + rolls[2] + total
    else
      current + total
    end
  end

  private

  attr_reader :rolls

  def strike?
    self[0] == 10
  end
end
```

spec/whatevz_spec.rb

``` ruby
require 'bowling'

RSpec.describe 'BowlingTest' do
  example "a game with no score is a 0" do
    score = Bowling.score([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    expect(score).to eq 0
  end

  example "a game without strikes or spares is the sum of the rolls" do
    score = Bowling.score([1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2])
    expect(score).to eq 30
  end

  example "strikes are 10 + the next two rolls" do
    score = Bowling.score([10, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    expect(score).to eq 19
  end

  example "spares are 10 + the next roll" do
    score = Bowling.score([9, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
    expect(score).to eq 14
  end

  example "a strike on the last frame is properly scored" do
    score = Bowling.score([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 10, 10])
    expect(score).to eq 30
  end

  example "a spare on the last frame is properly scored" do
    score = Bowling.score([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 1, 10])
    expect(score ).to eq 20
  end

  example "a perfect game" do
    score = Bowling.score([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])
    expect(score).to eq 300
  end
end
```

**Comment by JoshCheek** [comment]
```
rspec --fail-fast
F

Failures:

  1) BowlingTest a game with no score is a 0
     Failure/Error: self[0] == 10

     NoMethodError:
       undefined method `[]' for #<Bowling:0x007f815b0620c8>
     # ./lib/bowling.rb:24:in `strike?'
     # ./lib/bowling.rb:12:in `score'
     # ./lib/bowling.rb:3:in `score'
     # ./spec/whatevz_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.0006 seconds (files took 0.14433 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/whatevz_spec.rb:4 # BowlingTest a game with no score is a 0
```
